### ISSUE TITLE
Convert into classes

### ISSUE THREAD

**Issue by SupaFresh** [SupaFresh/PokemonMD-Toolkit#3]
/Maps/Operations.CS has these
![capturetemp](https://user-images.githubusercontent.com/31774924/46639435-dc468f00-cb1a-11e8-87d9-ee98a82d8501.PNG)

It's pretty self explanatory what to do here

**Comment by abc516** [comment]
Hi @SupaFresh do you need someone to take on this issue?

**Comment by SupaFresh** [comment]
big thanks to @rsilvanet for solving this!
